/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TresEnRaya;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Eduardo Dorado Esteban
 */
public class Vista extends javax.swing.JFrame {
   
    boolean estado = true;
    String siguienteTurno = "O";
    String turno = "X";
    JLabel labels [] = new JLabel [9];
    int victorias [][]= {
        {1,2,3},
        {4,5,6},
        {7,8,9},
        {1,4,7},
        {2,5,8},
        {3,6,9},
        {1,5,9},
        {7,5,3}
    };
    
    public Vista() {
        initComponents();
        this.setLocationRelativeTo(null);
        labels [0] = lbCasilla1;
        labels [1] = lbCasilla2;
        labels [2] = lbCasilla3;
        labels [3] = lbCasilla4;
        labels [4] = lbCasilla5;
        labels [5] = lbCasilla6;
        labels [6] = lbCasilla7;
        labels [7] = lbCasilla8;
        labels [8] = lbCasilla9;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPuntacion = new javax.swing.JPanel();
        jPanelCentral = new javax.swing.JPanel();
        lbCasilla1 = new javax.swing.JLabel();
        lbCasilla2 = new javax.swing.JLabel();
        lbCasilla3 = new javax.swing.JLabel();
        lbCasilla4 = new javax.swing.JLabel();
        lbCasilla5 = new javax.swing.JLabel();
        lbCasilla6 = new javax.swing.JLabel();
        lbCasilla7 = new javax.swing.JLabel();
        lbCasilla8 = new javax.swing.JLabel();
        lbCasilla9 = new javax.swing.JLabel();
        lbReiniciar = new javax.swing.JButton();
        lbTurno = new javax.swing.JLabel();
        lbPuntosO = new javax.swing.JLabel();
        lbPuntosX = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TresEnRaya");

        jPanelPuntacion.setBackground(new java.awt.Color(0, 0, 255));

        jPanelCentral.setBackground(new java.awt.Color(0, 0, 0));

        lbCasilla1.setBackground(new java.awt.Color(255, 255, 255));
        lbCasilla1.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
        lbCasilla1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCasilla1.setOpaque(true);
        lbCasilla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbCasilla1MousePressed(evt);
            }
        });

        lbCasilla2.setBackground(new java.awt.Color(255, 255, 255));
        lbCasilla2.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
        lbCasilla2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCasilla2.setOpaque(true);
        lbCasilla2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbCasilla2MousePressed(evt);
            }
        });

        lbCasilla3.setBackground(new java.awt.Color(255, 255, 255));
        lbCasilla3.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
        lbCasilla3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCasilla3.setOpaque(true);
        lbCasilla3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbCasilla3MousePressed(evt);
            }
        });

        lbCasilla4.setBackground(new java.awt.Color(255, 255, 255));
        lbCasilla4.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
        lbCasilla4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCasilla4.setOpaque(true);
        lbCasilla4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbCasilla4MousePressed(evt);
            }
        });

        lbCasilla5.setBackground(new java.awt.Color(255, 255, 255));
        lbCasilla5.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
        lbCasilla5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCasilla5.setOpaque(true);
        lbCasilla5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbCasilla5MousePressed(evt);
            }
        });

        lbCasilla6.setBackground(new java.awt.Color(255, 255, 255));
        lbCasilla6.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
        lbCasilla6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCasilla6.setOpaque(true);
        lbCasilla6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbCasilla6MousePressed(evt);
            }
        });

        lbCasilla7.setBackground(new java.awt.Color(255, 255, 255));
        lbCasilla7.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
        lbCasilla7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCasilla7.setOpaque(true);
        lbCasilla7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbCasilla7MousePressed(evt);
            }
        });

        lbCasilla8.setBackground(new java.awt.Color(255, 255, 255));
        lbCasilla8.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
        lbCasilla8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCasilla8.setOpaque(true);
        lbCasilla8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbCasilla8MousePressed(evt);
            }
        });

        lbCasilla9.setBackground(new java.awt.Color(255, 255, 255));
        lbCasilla9.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
        lbCasilla9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCasilla9.setOpaque(true);
        lbCasilla9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbCasilla9MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCentralLayout.createSequentialGroup()
                        .addComponent(lbCasilla1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbCasilla2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbCasilla3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCentralLayout.createSequentialGroup()
                        .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCentralLayout.createSequentialGroup()
                                .addComponent(lbCasilla7, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbCasilla8, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCentralLayout.createSequentialGroup()
                                .addComponent(lbCasilla4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(lbCasilla5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCasilla6, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCasilla9, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCasilla3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCasilla1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCasilla2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCasilla5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCasilla6, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCasilla4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCasilla8, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCasilla7, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCasilla9, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        lbReiniciar.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbReiniciar.setText("Reiniciar");
        lbReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbReiniciarActionPerformed(evt);
            }
        });

        lbTurno.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbTurno.setText("Turno de X");

        lbPuntosO.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbPuntosO.setText("0");

        lbPuntosX.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbPuntosX.setText("0");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel12.setText("X =");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel13.setText("O =");

        javax.swing.GroupLayout jPanelPuntacionLayout = new javax.swing.GroupLayout(jPanelPuntacion);
        jPanelPuntacion.setLayout(jPanelPuntacionLayout);
        jPanelPuntacionLayout.setHorizontalGroup(
            jPanelPuntacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPuntacionLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanelPuntacionLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jPanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
            .addGroup(jPanelPuntacionLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbPuntosX, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbPuntosO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );
        jPanelPuntacionLayout.setVerticalGroup(
            jPanelPuntacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPuntacionLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanelPuntacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbReiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(lbTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jPanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addGroup(jPanelPuntacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPuntosX, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPuntosO, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanelPuntacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanelPuntacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbCasilla1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCasilla1MousePressed
       pulsar(1);
    }//GEN-LAST:event_lbCasilla1MousePressed

    private void lbCasilla2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCasilla2MousePressed
       pulsar(2);
    }//GEN-LAST:event_lbCasilla2MousePressed

    private void lbCasilla3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCasilla3MousePressed
        pulsar(3);
    }//GEN-LAST:event_lbCasilla3MousePressed

    private void lbCasilla4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCasilla4MousePressed
        pulsar(4);
    }//GEN-LAST:event_lbCasilla4MousePressed

    private void lbCasilla5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCasilla5MousePressed
        pulsar(5);
    }//GEN-LAST:event_lbCasilla5MousePressed

    private void lbCasilla6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCasilla6MousePressed
        pulsar(6);
    }//GEN-LAST:event_lbCasilla6MousePressed

    private void lbCasilla7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCasilla7MousePressed
        pulsar(7);
    }//GEN-LAST:event_lbCasilla7MousePressed

    private void lbCasilla8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCasilla8MousePressed
        pulsar(8);
    }//GEN-LAST:event_lbCasilla8MousePressed

    private void lbCasilla9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCasilla9MousePressed
        pulsar(9);
    }//GEN-LAST:event_lbCasilla9MousePressed

    private void lbReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbReiniciarActionPerformed
        for ( int i = 0; i < labels.length; i++){
            labels[i].setText("");
            labels[i].setBackground(Color.white);
        }
        
        turno = siguienteTurno;
        if (siguienteTurno.equals("O")){
            siguienteTurno = "X";
        }
        else{
            siguienteTurno = "O";
        }
        lbTurno.setText("Turno de " + turno);
        estado = true;
    }//GEN-LAST:event_lbReiniciarActionPerformed

   
    public void pulsar (int cuadro){
        if (labels[cuadro-1].getText().equals("")&& estado) {
            labels [cuadro-1].setText(turno);
            cambiarTurno();
            comprobarGanador();
        }
        
    }
    
    public void cambiarTurno(){
        if(turno.equals("X")){
            turno = "O";
        }else {
            turno = "X";
        }
        lbTurno.setText("Turno de " + turno);
    }
    
    public void comprobarGanador(){
        for (int i = 0; i < victorias.length; i++){
            if(labels [victorias [i][0] -1].getText().equals("X")&&
                    labels [victorias [i][1] -1].getText().equals("X")&&
                    labels [victorias [i][2] -1].getText().equals("X")
                    )
            {
                System.out.println("Gano X");
                lbTurno.setText("Ganador X");
                lbPuntosX.setText(Integer.toString(Integer.parseInt(lbPuntosX.getText())+1));
                estado = false;
                labels [victorias [i][0] -1].setBackground(Color.red);
                labels [victorias [i][1] -1].setBackground(Color.red);
                labels [victorias [i][2] -1].setBackground(Color.red);
                
                
            }
            
            if (labels [victorias [i] [0] -1].getText().equals("O")&&
                    labels [victorias [i] [1] -1].getText().equals("O")&&
                    labels [victorias [i] [2] -1].getText().equals("O"))
            {
                System.out.println("Gano O");
                lbTurno.setText("Ganador O");
                lbPuntosO.setText(Integer.toString(Integer.parseInt(lbPuntosO.getText())+1));
                estado = false;
                labels [victorias [i][0] -1].setBackground(Color.red);
                labels [victorias [i][1] -1].setBackground(Color.red);
                labels [victorias [i][2] -1].setBackground(Color.red); 
            }
       
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelPuntacion;
    private javax.swing.JLabel lbCasilla1;
    private javax.swing.JLabel lbCasilla2;
    private javax.swing.JLabel lbCasilla3;
    private javax.swing.JLabel lbCasilla4;
    private javax.swing.JLabel lbCasilla5;
    private javax.swing.JLabel lbCasilla6;
    private javax.swing.JLabel lbCasilla7;
    private javax.swing.JLabel lbCasilla8;
    private javax.swing.JLabel lbCasilla9;
    private javax.swing.JLabel lbPuntosO;
    private javax.swing.JLabel lbPuntosX;
    private javax.swing.JButton lbReiniciar;
    private javax.swing.JLabel lbTurno;
    // End of variables declaration//GEN-END:variables
}
